In [ ]:
import torch

In [ ]:
float_32_tensor=torch.tensor([3.,6.,9.],
                             dtype=None,
                             device=None,
                             requires_grad=False)
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
some_tensor=torch.rand([3,4])
some_tensor

tensor([[0.0052, 0.4254, 0.3876, 0.7982],
        [0.1772, 0.2895, 0.0721, 0.9799],
        [0.0754, 0.1059, 0.2910, 0.2947]])

In [ ]:
print(f"the tensor dype is {some_tensor.dtype}")
print(f"the dimention is {some_tensor.shape}")
print(f"the device this tensor running on is{some_tensor.device}")

the tensor dype is torch.float32
the dimention is torch.Size([3, 4])
the device this tensor running on iscpu


In [ ]:
mat1= torch.tensor([[1,2,3],
                    [1,2,3]])

In [ ]:
mat2=torch.tensor([[1,2],
                   [3,4],
                   [5,6]])

In [ ]:
torch.matmul(mat1,mat2)

tensor([[22, 28],
        [22, 28]])

In [ ]:
mat1t=mat1.T
mat1t

tensor([[1, 1],
        [2, 2],
        [3, 3]])

In [ ]:
mat2t=mat2.T

In [ ]:
mat2t

tensor([[1, 3, 5],
        [2, 4, 6]])

In [ ]:
 x = torch.randn(4, 4)
 x

tensor([[-0.1372, -1.0987, -0.6342,  0.1902],
        [-0.1099,  0.2230,  0.8589,  0.3512],
        [ 0.8776, -0.7933, -1.1775, -1.3504],
        [ 1.3751, -2.1801, -0.0644, -1.4259]])

In [ ]:
x.size()

torch.Size([4, 4])

In [ ]:
y = x.view(16)
y

tensor([-0.1372, -1.0987, -0.6342,  0.1902, -0.1099,  0.2230,  0.8589,  0.3512,
         0.8776, -0.7933, -1.1775, -1.3504,  1.3751, -2.1801, -0.0644, -1.4259])

In [ ]:
y.size()

torch.Size([16])

In [ ]:
 z = x.view(-1, 8)
 z,z.size()

(tensor([[-0.1372, -1.0987, -0.6342,  0.1902, -0.1099,  0.2230,  0.8589,  0.3512],
         [ 0.8776, -0.7933, -1.1775, -1.3504,  1.3751, -2.1801, -0.0644, -1.4259]]),
 torch.Size([2, 8]))

In [ ]:
t=x.view(2,8)
t

tensor([[-0.1372, -1.0987, -0.6342,  0.1902, -0.1099,  0.2230,  0.8589,  0.3512],
        [ 0.8776, -0.7933, -1.1775, -1.3504,  1.3751, -2.1801, -0.0644, -1.4259]])

In [ ]:
a = torch.randn(1, 2, 3, 4)

In [ ]:
a

tensor([[[[ 0.3020,  0.2063, -0.3595,  1.0430],
          [ 0.6038,  0.0089, -0.7593,  0.4252],
          [ 0.5381,  0.1028,  1.7040,  1.0963]],

         [[-1.0787, -0.2112, -0.4321,  1.4533],
          [ 0.4972,  0.1868,  2.1881, -0.3930],
          [ 0.4174,  0.6285,  0.3204, -1.0021]]]])

In [ ]:
b = a.transpose(1, 2) 

In [ ]:
b

tensor([[[[ 0.3020,  0.2063, -0.3595,  1.0430],
          [-1.0787, -0.2112, -0.4321,  1.4533]],

         [[ 0.6038,  0.0089, -0.7593,  0.4252],
          [ 0.4972,  0.1868,  2.1881, -0.3930]],

         [[ 0.5381,  0.1028,  1.7040,  1.0963],
          [ 0.4174,  0.6285,  0.3204, -1.0021]]]])

In [ ]:
b.size()

torch.Size([1, 3, 2, 4])

In [ ]:
torch.tensor([2,2,3,4])

tensor([2, 2, 3, 4])

In [ ]:

a = torch.randn(2,2, 2, 3, 4)


In [ ]:
a

tensor([[[[[ 0.9976,  0.4327,  0.6513,  0.7918],
           [-1.7408,  0.1347,  0.9163, -0.3162],
           [ 2.6191, -2.5615, -1.1701, -2.0572]],

          [[-0.7559,  0.5594, -1.2724, -0.7931],
           [-1.6668, -0.3620, -0.8167,  0.6924],
           [ 0.2217,  0.2512,  0.8091,  1.2571]]],


         [[[ 2.0259, -0.7688,  0.9371, -0.3378],
           [-0.8037, -0.0850,  1.1457,  0.2119],
           [ 0.2395,  0.0861,  2.1299, -1.1529]],

          [[ 1.2497,  1.0408,  0.3726,  0.6585],
           [-0.4722,  0.1670,  0.3307,  0.2021],
           [-0.1970,  0.9722, -0.1382, -2.4629]]]],



        [[[[ 1.7692, -1.7638,  0.6609, -1.0238],
           [-0.5465,  0.6663,  1.2872,  1.5365],
           [ 0.7798, -0.8014,  2.3732,  0.4241]],

          [[-0.7378,  1.5862, -1.1529, -0.7888],
           [-0.4243,  0.2717, -1.8456,  0.8478],
           [ 0.3460,  1.2868,  0.5066, -0.5059]]],


         [[[-0.5347, -3.0140, -1.5322, -0.1490],
           [ 1.9617, -0.4606, -0.6249, -1.6111],
